---

- name: stop and disable tinc
  service:
    name: "{{ tinc_service_name }}"
    enabled: no
    state: stopped

- name: delete tinc netname directory
  file:
    path: "/etc/tinc/{{ tinc_netname }}"
    state: absent

- name: delete nets.boot
  file:
    path: /etc/tinc/nets.boot
    state: absent
